apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: consul-cni
  labels:
    app: consul-cni
    release: cni-poc
rules:
- apiGroups: [""]
  resources:
  - pods
  - nodes
  verbs:
  - get
