apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
metadata:
  namespace: istio-system
  name: istiocontrolplane
spec:
  hub: docker.io/querycapistio
  profile: minimal
  components:
    base:
      enabled: true
    cni:
      enabled: true
    ingressGateways:
      - enabled: true
        name: istio-ingressgateway
        k8s:
          hpaSpec:
            maxReplicas: 1
          nodeSelector:
            ingress-ready: "true"
          service:
            type: NodePort
          overlays:
            - apiVersion: v1
              kind: Service
              name: istio-ingressgateway
              patches:
                - path: spec.ports
                  value:
                    - name: status-port
                      port: 15021
                      targetPort: 15021
                      nodePort: 30002
                      protocol: TCP
                    - name: http2
                      port: 80
                      targetPort: 8080
                      nodePort: 30000
                      protocol: TCP
                    - name: https
                      port: 443
                      targetPort: 8443
                      nodePort: 30001
                      protocol: TCP
            - apiVersion: policy/v1beta1
              kind: PodDisruptionBudget
              name: istio-ingressgateway
              patches:
                - path: spec.minAvailable
                  value: 0
    pilot:
      enabled: true
      k8s:
        hpaSpec:
          maxReplicas: 1
        overlays:
          - apiVersion: policy/v1beta1
            kind: PodDisruptionBudget
            name: istiod
            patches:
              - path: spec.minAvailable
                value: 0
  meshConfig:
    accessLogFile: "/dev/stdout"
    accessLogEncoding: "JSON"
  values:
    global:
      imagePullPolicy: IfNotPresent
      proxy_init:
        image: istio-proxyv2
    pilot:
      image: istio-pilot
    cni:
      image: istio-install-cni
      cniBinDir: /opt/cni/bin
      cniConfDir: /etc/cni/net.d
      repair:
        enabled: true
      logLevel: info
      excludeNamespaces:
        - istio-system
        - kube-system
        - istio-operator
